# Generated by Django 4.2.7 on 2024-01-06 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0003_emailverifcation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailVerifcation',
            new_name='EmailVerification',
        ),
    ]
