# Generated by Django 4.2.7 on 2024-01-09 11:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0005_alter_myuser_groups_alter_myuser_nickname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='nickname',
            field=models.CharField(max_length=6, unique=True, validators=[django.core.validators.RegexValidator(message='닉네임은 한글, 숫자, 영어 2~6글자입니다.', regex='^\\p{L}\\p{N}]{2,6}$')]),
        ),
    ]
