# Generated by Django 4.2.7 on 2024-01-05 07:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_category_name_alter_section_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='subsection',
            name='name',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message='이름은 2~16글자의 한국어, 일본어, 알파벳, 숫자만 포함할 수 있습니다.', regex='^[\\uAC00-\\uD7AF\\u3040-\\u30FF\\u31F0-\\u31FFa-zA-Z0-9]{2,16}$')]),
        ),
    ]
