# Generated by Django 4.2.7 on 2023-12-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsection',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
