# Generated by Django 4.2.7 on 2024-01-02 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_subsection_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='edited_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
