# Generated by Django 4.2.7 on 2024-01-02 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_edited_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
